[package]
name = "linfa-knn"
version = "0.1.0"
edition = "2024"

[dependencies]
linfa = { version = "0.8.1", path = "../.." }
linfa-nn = { version = "0.8.1", path = "../linfa-nn" }
ndarray = "0.17.2"
num-traits = "0.2.19"

